/*
 * This file was @generated by mochi_gen_py. Do not modify this file by hand!!
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// clang-format off

#pragma once

#include <limits>
#include <mochi_core/utils/reflection.h>
#include <mochi_physics/mochi_physics.h>

MOCHI_ENUM_BEGIN(mochi::ActorType)
MOCHI_ENUM_ITEM(None)
MOCHI_ENUM_ITEM(Rigid)
MOCHI_ENUM_ITEM(Soft)
MOCHI_ENUM_ITEM(Articulated)
MOCHI_ENUM_ITEM(Shell)
MOCHI_ENUM_ITEM(Rod)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_END()

MOCHI_ENUM_BEGIN(mochi::BoundarySubsamplingStrategy)
MOCHI_ENUM_ITEM(UniformProbability)
MOCHI_ENUM_ITEM(AreaProportional)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_END()

MOCHI_ENUM_BEGIN(mochi::ActorBoundaryElementType)
MOCHI_ENUM_ITEM(P1Q1)
MOCHI_ENUM_ITEM(P1Q3)
MOCHI_ENUM_ITEM(P1Q6)
MOCHI_ENUM_ITEM(ExperimentalP1Q7)
MOCHI_ENUM_ITEM(ExperimentalP1Q12)
MOCHI_ENUM_ITEM(ExperimentalP1Q16)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_ITEM(Default)
MOCHI_ENUM_END()

MOCHI_ENUM_BEGIN(mochi::ActorSegmentElementType)
MOCHI_ENUM_ITEM(P1Q1)
MOCHI_ENUM_ITEM(P1Q2)
MOCHI_ENUM_ITEM(P1Q3)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_ITEM(Default)
MOCHI_ENUM_END()

MOCHI_ENUM_BEGIN(mochi::ConstraintType)
MOCHI_ENUM_ITEM(None)
MOCHI_ENUM_ITEM(ArticulatedSingleDofRange)
MOCHI_ENUM_ITEM(Articulated3dRotationRange)
MOCHI_ENUM_ITEM(ArticulatedSingleDofTarget)
MOCHI_ENUM_ITEM(Articulated3dRotationTarget)
MOCHI_ENUM_ITEM(JointRotationRange)
MOCHI_ENUM_ITEM(JointRotationTracking)
MOCHI_ENUM_ITEM(RigidPivotPosition)
MOCHI_ENUM_ITEM(RigidPivotToRigidTarget)
MOCHI_ENUM_ITEM(RigidPivotRotation)
MOCHI_ENUM_ITEM(RigidPrismaticJoint)
MOCHI_ENUM_ITEM(RigidSphericalJoint)
MOCHI_ENUM_ITEM(DeformableNodePosition)
MOCHI_ENUM_ITEM(DeformableNodeToRigid)
MOCHI_ENUM_ITEM(DeformableNodeToDeformableNode)
MOCHI_ENUM_ITEM(RodElementRotationToRigid)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_END()

MOCHI_ENUM_BEGIN(mochi::PoseConstraintType)
MOCHI_ENUM_ITEM(Joint)
MOCHI_ENUM_ITEM(LinkTranslation)
MOCHI_ENUM_ITEM(LinkRotation)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_ITEM(Invalid)
MOCHI_ENUM_END()

MOCHI_ENUM_BEGIN(mochi::QueryType)
MOCHI_ENUM_ITEM(NodePositions)
MOCHI_ENUM_ITEM(ElementsDeformationGradient)
MOCHI_ENUM_ITEM(SurfaceNodePositions)
MOCHI_ENUM_ITEM(SurfaceNodeNormals)
MOCHI_ENUM_ITEM(VisualNodePositions)
MOCHI_ENUM_ITEM(VisualNodeNormals)
MOCHI_ENUM_ITEM(ContactPoints)
MOCHI_ENUM_ITEM(ElasticEnergy)
MOCHI_ENUM_ITEM(NodeContactForces)
MOCHI_ENUM_ITEM(ConstraintForce)
MOCHI_ENUM_ITEM(ArticulatedControllerForce)
MOCHI_ENUM_ITEM(SdfDistances)
MOCHI_ENUM_ITEM(TotalContactForce)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_END()

MOCHI_ENUM_BEGIN(mochi::IncludeNestedActors)
MOCHI_ENUM_ITEM(No)
MOCHI_ENUM_ITEM(Yes)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_END()

#include <mochi_physics/mochi_physics_experimental.h>

MOCHI_STRUCT_BEGIN_EX(mochi::Handle)
MOCHI_FIELD(value)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::SceneHandle)
MOCHI_BASE_CLASS(mochi::Handle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ActorHandle)
MOCHI_BASE_CLASS(mochi::Handle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ShapeHandle)
MOCHI_BASE_CLASS(mochi::Handle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::CallbackHandle)
MOCHI_BASE_CLASS(mochi::Handle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ConstraintHandle)
MOCHI_BASE_CLASS(mochi::Handle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::StateHandle)
MOCHI_BASE_CLASS(mochi::Handle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::QueryHandle)
MOCHI_BASE_CLASS(mochi::Handle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::SolverParams)
MOCHI_FIELD(nonLinearSolver)
MOCHI_FIELD(linearSolver)
MOCHI_FIELD(integrationMethod)
MOCHI_FIELD(experimentalEval)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RecenteringParams)
MOCHI_FIELD(useRecentering)
MOCHI_FIELD(rotationEpsilonDeg) MOCHI_ATTRIBUTE(Units("deg"))
MOCHI_FIELD(translationEpsilon) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::BoundarySubsamplingParams)
MOCHI_FIELD(subsamplingDensity)
MOCHI_FIELD(strategy)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ContactPairParamsOverride)
MOCHI_FIELD(penaltyCoefficient) MOCHI_ATTRIBUTE(Units("Pa/m"))
MOCHI_FIELD(frictionFalloffVel) MOCHI_ATTRIBUTE(Units("m/s"))
MOCHI_FIELD(viscousFrictionCoefficient) MOCHI_ATTRIBUTE(Units("s/m"))
MOCHI_FIELD(coulombFrictionCoefficient)
MOCHI_FIELD(normalViscousDampingCoefficient) MOCHI_ATTRIBUTE(Units("s/m"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ArticulatedShapeInfo)
// MOCHI_FIELD(rootFromLinksAtRest) // TODO: Span not supported
// MOCHI_FIELD(linkNames) // TODO: Span not supported
// MOCHI_FIELD(parents) // TODO: Span not supported
// MOCHI_FIELD(jointTypes) // TODO: Span not supported
// MOCHI_FIELD(cycles) // TODO: Span not supported
// MOCHI_FIELD(jointAxes) // TODO: Span not supported
// MOCHI_FIELD(dofInfo) // TODO: Span not supported
// MOCHI_FIELD(jointFromChildLink) // TODO: Span not supported
// MOCHI_FIELD(parentLinkFromJoint) // TODO: Span not supported
// MOCHI_FIELD(jointMinLimits) // TODO: Span not supported
// MOCHI_FIELD(jointMaxLimits) // TODO: Span not supported
// MOCHI_FIELD(jointNames) // TODO: Span not supported
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::Scene)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::StepInfo)
// MOCHI_FIELD(scene) // TODO: Pointer types not supported
MOCHI_FIELD(timeStepSec) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RigidActorParams)
MOCHI_FIELD(name)
MOCHI_FIELD(layer)
MOCHI_FIELD(shape)
MOCHI_FIELD(worldFromLocal)
MOCHI_FIELD(colliderType)
MOCHI_FIELD(isStatic)
MOCHI_FIELD(contact)
MOCHI_FIELD(sdf)
MOCHI_FIELD(hasGravity)
MOCHI_FIELD(density) MOCHI_ATTRIBUTE(Units("kg/m^3"))
MOCHI_FIELD(mass) MOCHI_ATTRIBUTE(Units("kg"))
MOCHI_FIELD(centerOfMass) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(momentOfInertia) MOCHI_ATTRIBUTE(Units("kg*m^2"))
MOCHI_FIELD(boundaryElementType)
MOCHI_FIELD(boundarySubsampling)
MOCHI_FIELD(linearVelocity) MOCHI_ATTRIBUTE(Units("m/s"))
MOCHI_FIELD(angularVelocity) MOCHI_ATTRIBUTE(Units("rad/s"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::SoftActorParams)
MOCHI_FIELD(name)
MOCHI_FIELD(layer)
MOCHI_FIELD(worldFromLocal)
MOCHI_FIELD(shape)
MOCHI_FIELD(material)
MOCHI_FIELD(contact)
MOCHI_FIELD(hasGravity)
MOCHI_FIELD(hasInertia)
MOCHI_FIELD(hasStress)
MOCHI_FIELD(boundaryElementType)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ArticulatedJointParams)
MOCHI_FIELD(name)
MOCHI_FIELD(type)
MOCHI_FIELD(parentLinkFromJoint)
MOCHI_FIELD(axis)
MOCHI_FIELD(friction)
MOCHI_FIELD(inertia)
MOCHI_FIELD(minLimit)
MOCHI_FIELD(maxLimit)
MOCHI_FIELD(limitStiffness)
MOCHI_FIELD(limitDamping)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ArticulatedLinkParams)
MOCHI_FIELD(name)
MOCHI_FIELD(parentLink)
MOCHI_FIELD(parentJointFromLink)
MOCHI_FIELD(shape)
MOCHI_FIELD(layer)
MOCHI_FIELD(colliderType)
MOCHI_FIELD(contact)
MOCHI_FIELD(hasGravity)
MOCHI_FIELD(density) MOCHI_ATTRIBUTE(Units("kg/m^3"))
MOCHI_FIELD(mass) MOCHI_ATTRIBUTE(Units("kg"))
MOCHI_FIELD(centerOfMass) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(momentOfInertia) MOCHI_ATTRIBUTE(Units("kg*m^2"))
MOCHI_FIELD(boundaryElementType)
MOCHI_FIELD(boundarySubsampling)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ArticulatedSkinParams)
MOCHI_FIELD(shape)
MOCHI_FIELD(layer)
MOCHI_FIELD(contact)
MOCHI_FIELD(boundaryElementType)
MOCHI_FIELD(boundarySubsampling)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ArticulatedCycleJointParams)
MOCHI_FIELD(parentLink)
MOCHI_FIELD(childLink)
MOCHI_FIELD(jointFromChildLink)
MOCHI_FIELD(stiffness)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ArticulatedActorParams)
MOCHI_FIELD(name)
MOCHI_FIELD(worldFromRoot)
MOCHI_FIELD(cycles)
MOCHI_FIELD(joints)
MOCHI_FIELD(links)
MOCHI_FIELD(skin)
MOCHI_FIELD(jointVelocities)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::SoftSkinnedActorParams)
MOCHI_FIELD(skeletonParams)
MOCHI_FIELD(softParams)
MOCHI_FIELD(softAttachLinks)
MOCHI_FIELD(enableCollidingLinks)
MOCHI_FIELD(hasGravity)
MOCHI_FIELD(hasInertia)
MOCHI_FIELD(hasStress)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ConstraintParams)
MOCHI_FIELD(stiffness)
MOCHI_FIELD(damping)
MOCHI_FIELD(saturation)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RigidSphericalJointConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(localPosA) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(localPosB) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(actorA)
MOCHI_FIELD(actorB)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RigidPrismaticJointConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(freeAxis)
MOCHI_FIELD(actorA)
MOCHI_FIELD(actorB)
MOCHI_FIELD(max) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(min) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::DeformableNodeToDeformableNodeConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(nodeIndexA)
MOCHI_FIELD(nodeIndexB)
MOCHI_FIELD(actorA)
MOCHI_FIELD(actorB)
MOCHI_FIELD(findClosest)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RodElementRotationToRigidConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(refFrameRotVec) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(rigidActor)
MOCHI_FIELD(rodActor)
MOCHI_FIELD(elementIndex)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::DeformableNodeToRigidConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(rigidLocalPos) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(deformableNodeIndex)
MOCHI_FIELD(rigidActor)
MOCHI_FIELD(deformableActor)
MOCHI_FIELD(findClosest)
MOCHI_FIELD(fixToDeformablePos)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::JointRotationRangeConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(refFrameRotVec) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(angleRangeX) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(angleRangeY) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(angleRangeZ) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(actorA)
MOCHI_FIELD(actorB)
MOCHI_FIELD(rangeAroundRest)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RigidPivotPositionConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(targetPosition) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(localPosition) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(actor)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RigidPivotToRigidTargetConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(targetTransform)
MOCHI_FIELD(localPosition) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(actor)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RigidPivotRotationConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(targetRotation) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(localRotation) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(actor)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::DeformableNodePositionConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(nodeIndex)
MOCHI_FIELD(position) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(actor)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::JointRotationTrackingConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(refFrameRotVec) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(actorA)
MOCHI_FIELD(actorB)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ArticulatedSingleDofTargetConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(actor)
MOCHI_FIELD(jointIndex)
MOCHI_FIELD(dofIndex)
MOCHI_FIELD(targetValue)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::Articulated3dRotationTargetConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(actor)
MOCHI_FIELD(jointIndex)
MOCHI_FIELD(target)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ArticulatedSingleDofRangeConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(actor)
MOCHI_FIELD(jointIndex)
MOCHI_FIELD(dofIndex)
MOCHI_FIELD(minValue)
MOCHI_FIELD(maxValue)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::Articulated3dRotationRangeConstraintParams)
MOCHI_BASE_CLASS(mochi::ConstraintParams)
MOCHI_FIELD(actor)
MOCHI_FIELD(jointIndex)
MOCHI_FIELD(minValues) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_FIELD(maxValues) MOCHI_ATTRIBUTE(Units("rad"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::ContactPoint)
MOCHI_FIELD(actorA)
MOCHI_FIELD(actorB)
MOCHI_FIELD(distance) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(posA) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(posB) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_FIELD(normal)
MOCHI_FIELD(force) MOCHI_ATTRIBUTE(Units("N"))
MOCHI_FIELD(pointVelocityA) MOCHI_ATTRIBUTE(Units("m/s"))
MOCHI_FIELD(pointVelocityB) MOCHI_ATTRIBUTE(Units("m/s"))
MOCHI_FIELD(sampleIndex)
MOCHI_FIELD(intWeight)
MOCHI_FIELD(elementIndex)
MOCHI_FIELD(parametricCoords)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::NodeContactForce)
MOCHI_FIELD(index)
MOCHI_FIELD(force) MOCHI_ATTRIBUTE(Units("N"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::SdfDistances)
// MOCHI_FIELD(sampleIndices) // TODO: Span not supported
// MOCHI_FIELD(worldPositions) // TODO: Span not supported
// MOCHI_FIELD(distances) // TODO: Span not supported
// MOCHI_FIELD(distanceGrads) // TODO: Span not supported
MOCHI_FIELD(maxSdfFarDistanceEvaluation) MOCHI_ATTRIBUTE(Units("m"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::AsyncStepParams)
MOCHI_FIELD(useFixedTimeStep)
MOCHI_FIELD(fixedTimeStepSeconds) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_FIELD(dynamicTimeStepMinSeconds) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_FIELD(dynamicTimeStepMaxSeconds) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::PerformanceStats)
MOCHI_FIELD(totalStepDurationSec) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_FIELD(solveStepDurationSec) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_FIELD(preStepCallbacksDurationSec) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_FIELD(postStepCallbacksDurationSec) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_FIELD(recordingStepDurationSec) MOCHI_ATTRIBUTE(Units("s"))
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::SolverStats)
MOCHI_FIELD(maxNonLinearIters)
MOCHI_FIELD(residualNorm)
MOCHI_FIELD(maxLineSearchIters)
MOCHI_FIELD(convergenceStatus)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::RecordingParams)
MOCHI_FIELD(recordActorMeshes)
MOCHI_FIELD(recordActorLocalToGlobalMap)
MOCHI_FIELD(recordActorMassMatrix)
MOCHI_FIELD(recordTargetState)
MOCHI_FIELD(recordDynamicActorState)
MOCHI_FIELD(recordStaticActorState)
MOCHI_FIELD(recordContactPoints)
MOCHI_FIELD(recordNodeContactForces)
MOCHI_FIELD(recordSdfDistances)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::PoseTrackingParams)
MOCHI_FIELD(stiffness)
MOCHI_FIELD(damping)
MOCHI_FIELD(saturation)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::PoseControllerParams)
MOCHI_FIELD(linkPosTracking)
MOCHI_FIELD(linkRotTracking)
MOCHI_FIELD(jointTracking)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::PoseConstraintInfo)
MOCHI_FIELD(handle)
MOCHI_FIELD(type)
MOCHI_FIELD(link)
MOCHI_FIELD(parent)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::DebugDrawSpheres)
// MOCHI_FIELD(positions) // TODO: Span not supported
// MOCHI_FIELD(radii) // TODO: Span not supported
// MOCHI_FIELD(colors) // TODO: Span not supported
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::DebugDrawLineVertices)
// MOCHI_FIELD(positions) // TODO: Span not supported
// MOCHI_FIELD(colors) // TODO: Span not supported
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::DebugDrawData)
MOCHI_FIELD(lineVertices)
MOCHI_FIELD(spheres)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::Context)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::Actor)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::Constraint)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::AsyncScene)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::DebugDraw)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(mochi::DebugServer)
MOCHI_STRUCT_END_EX()

// clang-format on
