# This file was @generated by mochi_gen_py. Do not modify this file by hand!!
#
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pyre-strict

from typing import Any, Callable, Iterator, Optional, Sequence, overload
import numpy as np
import numpy.typing as npt
import mochi_physics

########################################################################################

def load_from_file(path: str) -> mochi_physics.ModelData:
    """Load model data from a file. Then, :func:`~superdex.physics.model.auto_correct`
    and :func:`~superdex.physics.model.validate` will be called automatically.

    Supported formats: JSON (.mochi.json), HDF5 (.mochi.h5), OBJ (.obj), OFF (.off),
    PLY (.ply), and STL (.stl).

    Args:
        path (str): File path to load.

    Returns:
        :class:`~superdex.physics.ModelData` that was loaded.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def load_from_file_unchecked(path: str) -> mochi_physics.ModelData:
    """Load model data from a file without calling
    :func:`~superdex.physics.model.auto_correct` nor
    :func:`~superdex.physics.model.validate`. Can be used to load a model that is
    not currently in a valid state.

    Supported formats: JSON (.mochi.json), HDF5 (.mochi.h5), OBJ (.obj), OFF (.off),
    PLY (.ply), and STL (.stl).

    Args:
        path (str): File path to load.

    Returns:
        :class:`~superdex.physics.ModelData` that was loaded.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

@overload
def load_from_bytes(data: mochi_physics.ArrayLikeChar) -> mochi_physics.ModelData:
    """Convenience overload using :class:`LEGACY <superdex.physics.MeshFileType>`.

    Args:
        data (ArrayLikeChar): File contents in memory.

    Returns:
        :class:`~superdex.physics.ModelData` that was loaded.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

@overload
def load_from_bytes(
    data: mochi_physics.ArrayLikeChar,
    format: mochi_physics.MeshFileType | int,
) -> mochi_physics.ModelData:
    """Load model data from a file in memory. Then,
    :func:`~superdex.physics.model.auto_correct` and
    :func:`~superdex.physics.model.validate` will be called automatically.

    Args:
        data (ArrayLikeChar): File contents in memory.
        format (MeshFileType | int): Mesh file format hint. When :class:`LEGACY
            <superdex.physics.MeshFileType>` (the default), auto-detects between
            HDF5 and JSON via header bytes. When a surface mesh format (:class:`PLY
            <superdex.physics.MeshFileType>`, :class:`OFF
            <superdex.physics.MeshFileType>`, :class:`STL
            <superdex.physics.MeshFileType>`, :class:`OBJ
            <superdex.physics.MeshFileType>`), dispatches directly to that reader.

    Returns:
        :class:`~superdex.physics.ModelData` that was loaded.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

@overload
def load_from_bytes_unchecked(
    data: mochi_physics.ArrayLikeChar,
) -> mochi_physics.ModelData:
    """Convenience overload using :class:`LEGACY <superdex.physics.MeshFileType>`.

    Args:
        data (ArrayLikeChar): File contents in memory.

    Returns:
        :class:`~superdex.physics.ModelData` that was loaded.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

@overload
def load_from_bytes_unchecked(
    data: mochi_physics.ArrayLikeChar,
    format: mochi_physics.MeshFileType | int,
) -> mochi_physics.ModelData:
    """Load model data from a file in memory without calling
    :func:`~superdex.physics.model.auto_correct` nor
    :func:`~superdex.physics.model.validate`. Can be used to load a model that is
    not currently in a valid state.

    Args:
        data (ArrayLikeChar): File contents in memory.
        format (MeshFileType | int): Mesh file format hint. When :class:`LEGACY
            <superdex.physics.MeshFileType>` (the default), auto-detects between
            HDF5 and JSON via header bytes. When a surface mesh format (:class:`PLY
            <superdex.physics.MeshFileType>`, :class:`OFF
            <superdex.physics.MeshFileType>`, :class:`STL
            <superdex.physics.MeshFileType>`, :class:`OBJ
            <superdex.physics.MeshFileType>`), dispatches directly to that reader.

    Returns:
        :class:`~superdex.physics.ModelData` that was loaded.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

@overload
def save_to_file(
    data: mochi_physics.ModelData,
    path: str,
    format: mochi_physics.FileFormat | int,
) -> None:
    """Save a model to a file of the specified format.

    Args:
        data (ModelData): Model data to write.
        path (str): File path to write.
        format (FileFormat | int): File format to write.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Note:
        Creates the destination directories if necessary.

    Warning:
        Some model files contain additional data for experimental features (e.g.
        ROMs), which cannot be represented by the
        :class:`~superdex.physics.ModelData` struct. That data will be lost if you
        use the :class:`~superdex.physics.ModelData` struct to save over the
        original file.
    """

@overload
def save_to_file(
    data: mochi_physics.ModelDataView,
    path: str,
    format: mochi_physics.FileFormat | int,
) -> None:
    """Save a model to a file of the specified format.

    Args:
        data (ModelDataView): A non-owning view of the model data to write.
        path (str): File path to write.
        format (FileFormat | int): File format to write.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Note:
        Creates the destination directories if necessary.

    Warning:
        Some model files contain additional data for experimental features (e.g.
        ROMs), which cannot be represented by the
        :class:`~superdex.physics.ModelData` struct. That data will be lost if you
        use the :class:`~superdex.physics.ModelData` struct to save over the
        original file.
    """

def save_to_json_string(data: mochi_physics.ModelData) -> str:
    """Save a model to a JSON string in memory.

    Args:
        data (ModelData): Model data to serialize.

    Returns:
        JSON string containing the model data.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def validate(data: mochi_physics.ModelDataView) -> None:
    """Check the model for errors.

    Args:
        data (ModelDataView): Non-owning view of the model data to check.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

def auto_correct(data: mochi_physics.ModelData) -> None:
    """Apply automatic in-place fixes to the model data, such as normalizing vectors
    and weights.

    Args:
        data (ModelData): :class:`~superdex.physics.ModelData` to check and possibly
            modify.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

@overload
def bake_transform(
    data: mochi_physics.ModelData,
    scale: mochi_physics.Real3Like = ...,
    rotation: mochi_physics.QuaternionLike = ...,
    translation: mochi_physics.Real3Like = ...,
) -> None:
    """Modify the :class:`~superdex.physics.ModelData` by applying a scale, rotation,
    and translation (in that order).

    Args:
        data (ModelData): :class:`~superdex.physics.ModelData` to modify.
        scale (Real3Like): Scale to apply (possibly non-uniform, i.e., 3 unequal
            absolute values).
        rotation (QuaternionLike): Rotation to apply (quaternion in [x, y, z, w]
            order).
        translation (Real3Like): Translation to apply.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Note:
        Negative scale can be used to mirror the model. In that case,
        :func:`~superdex.physics.model.flip_winding_order` will be called
        automatically to avoid turning the model inside out.

    Note:
        If :attr:`~superdex.physics.ModelData.element_frame_axes` is present, axes
        are transformed as normal directions using the inverse-transpose of the
        scale-rotation transform, then normalized. This preserves orthogonality with
        transformed polyline element tangents under non-uniform scale.

    Warning:
        Some model data cannot bake arbitrary non-uniform scale, resulting in an
        error.

    Warning:
        Precomputed grid SDF data is preserved only when ``scale`` is uniform by
        absolute value. Non-uniform scale by absolute value discards the precomputed
        SDF. If an SDF collider later requires SDF data, Mochi regenerates the SDF
        from the transformed mesh at runtime, which may be expensive.
    """

@overload
def bake_transform(
    data: mochi_physics.ModelData,
    scale: mochi_physics.Real3Like = ...,
    transform: mochi_physics.TransformRT = ...,
) -> None:
    """Modify the :class:`~superdex.physics.ModelData` by applying a scale, rotation,
    and translation (in that order).

    Takes a combined :class:`~superdex.physics.TransformRT` instead of separate
    rotation and translation.

    Args:
        data (ModelData): :class:`~superdex.physics.ModelData` to modify.
        scale (Real3Like): Scale to apply (possibly non-uniform, i.e., 3 unequal
            absolute values).
        transform (TransformRT): Combined rotation and translation to apply.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Note:
        Negative scale can be used to mirror the model. In that case,
        :func:`~superdex.physics.model.flip_winding_order` will be called
        automatically to avoid turning the model inside out.

    Note:
        If :attr:`~superdex.physics.ModelData.element_frame_axes` is present, axes
        are transformed as normal directions using the inverse-transpose of the
        scale-rotation transform, then normalized. This preserves orthogonality with
        transformed polyline element tangents under non-uniform scale.

    Warning:
        Some model data cannot bake arbitrary non-uniform scale, resulting in an
        error.

    Warning:
        Precomputed grid SDF data is preserved only when ``scale`` is uniform by
        absolute value. Non-uniform scale by absolute value discards the precomputed
        SDF. If an SDF collider later requires SDF data, Mochi regenerates the SDF
        from the transformed mesh at runtime, which may be expensive.
    """

@overload
def bake_coordinate_space_transform(
    data: mochi_physics.MeshData,
    from_space: mochi_physics.CoordinateSpace,
    to_space: mochi_physics.CoordinateSpace,
) -> None:
    """Modify the :class:`~superdex.physics.MeshData` to convert it from one
    :class:`~superdex.physics.CoordinateSpace` to another.

    If the transformation flips handedness, the mesh winding order will also be
    reversed.

    Args:
        data (MeshData): :class:`~superdex.physics.MeshData` to modify.
        from_space (CoordinateSpace): Coordinate space the mesh is currently
            expressed in.
        to_space (CoordinateSpace): Coordinate space to convert the mesh to.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Note:
        The conversion is exact when
        :attr:`~superdex.physics.CoordinateSpace.units_per_meter` is unchanged,
        because it only permutes and negates axes.
    """

@overload
def bake_coordinate_space_transform(
    data: mochi_physics.ModelData,
    from_space: mochi_physics.CoordinateSpace,
    to_space: mochi_physics.CoordinateSpace,
) -> None:
    """Modify the :class:`~superdex.physics.ModelData` to convert it from one
    :class:`~superdex.physics.CoordinateSpace` to another.

    All spatial data within the model will be transformed. If the transformation
    flips handedness, the winding order of any meshes will be reversed.

    Args:
        data (ModelData): :class:`~superdex.physics.ModelData` to modify.
        from_space (CoordinateSpace): Coordinate space the model is currently
            expressed in.
        to_space (CoordinateSpace): Coordinate space to convert the model to.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Note:
        The conversion is exact when
        :attr:`~superdex.physics.CoordinateSpace.units_per_meter` is unchanged,
        except for orientations stored as a quaternion (implicit box and grid SDF),
        which cannot represent a 90 degree rotation exactly.
    """

def bake_sdf(
    data: mochi_physics.ModelData,
    params: mochi_physics.GridSdfParams = ...,
) -> None:
    """Compute and bake an SDF grid into the model data.

    Computes a signed-distance field (SDF) grid from the model's mesh (triangular or
    tetrahedral) and stores it in the model's
    :attr:`~superdex.physics.ModelData.sdf` field, replacing any existing SDF.

    Args:
        data (ModelData): :class:`~superdex.physics.ModelData` to modify. Must
            contain a triangle or tetrahedral mesh.
        params (GridSdfParams): Parameters to control grid resolution and padding.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.

    Warning:
        SDF computation may be slow.
    """

@overload
def flip_winding_order(data: mochi_physics.MeshData) -> None:
    """Flip mesh winding order by swapping the connectivity indices within each
    element.

    Args:
        data (MeshData): :class:`~superdex.physics.MeshData` to modify.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """

@overload
def flip_winding_order(data: mochi_physics.ModelData) -> None:
    """Flip mesh winding order by swapping the connectivity indices within each
    element.

    Operates on the simulation mesh (:attr:`~superdex.physics.ModelData.mesh`),
    visual mesh (:attr:`~superdex.physics.ModelData.visual_mesh`), and contact skin
    (:attr:`~superdex.physics.ModelData.contact_skin_mesh`) when present. Implicit
    shapes and SDF data are not modified.

    Args:
        data (ModelData): :class:`~superdex.physics.ModelData` to modify.

    Raises:
        :class:`~superdex.physics.Error`: If an error occurs.
    """
