/*
 * This file was @generated by mochi_gen_py. Do not modify this file by hand!!
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// clang-format off

#pragma once

#include <limits>
#include <mochi_core/utils/reflection.h>
#include <superdex_robotics/superdex_robotics.h>

MOCHI_ENUM_BEGIN(superdex::robotics::BotFileType)
MOCHI_ENUM_ITEM(BotPrefab)
MOCHI_ENUM_ITEM(ModBotPrefab)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_END()

MOCHI_ENUM_BEGIN(superdex::robotics::LinkTransformSpace)
MOCHI_ENUM_ITEM(ParentFromLink)
MOCHI_ENUM_ITEM(RootFromParent)
MOCHI_ENUM_COUNT(Count)
MOCHI_ENUM_END()

#include <superdex_robotics/controllers/controller_basic_jsc_pd.h>
#include <superdex_robotics/controllers/controller_basic_osc_pd.h>
#include <superdex_robotics/controllers/controller_mochi_articulated_pose.h>
#include <superdex_robotics/sensors/camera_sensor.h>
#include <superdex_robotics/actuators/actuator_base.h>
#include <superdex_robotics/utils/bot_utils.h>
#include <superdex_robotics/utils/superdex_robotics_api_checks.generated.h>

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::RoboticsHandle)
MOCHI_FIELD(value)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::BotHandle)
MOCHI_BASE_CLASS(superdex::robotics::RoboticsHandle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerHandle)
MOCHI_BASE_CLASS(superdex::robotics::RoboticsHandle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::SensorHandle)
MOCHI_BASE_CLASS(superdex::robotics::RoboticsHandle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ActuatorHandle)
MOCHI_BASE_CLASS(superdex::robotics::RoboticsHandle)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::RoboticsContext)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ComponentBase)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerBase)
MOCHI_BASE_CLASS(superdex::robotics::ComponentBase)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerBasicOscPdObsv)
MOCHI_FIELD(dofPositions)
MOCHI_FIELD(dofVelocities)
MOCHI_FIELD(worldFromRoot)
MOCHI_FIELD(worldFromEELink)
MOCHI_FIELD(eeJacobian)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerBasicOscPdTarget)
MOCHI_FIELD(rootFromTargetEE)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerBasicOscPd)
MOCHI_BASE_CLASS(superdex::robotics::ControllerBase)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerMochiArticulatedPoseObsv)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerMochiArticulatedPoseTarget)
MOCHI_FIELD(worldFromRoot)
MOCHI_FIELD(localToParentTransforms)
MOCHI_FIELD(poseDofs)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerMochiArticulatedPose)
MOCHI_BASE_CLASS(superdex::robotics::ControllerBase)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::Bot)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerBasicJscPdObsv)
MOCHI_FIELD(dofPositions)
MOCHI_FIELD(dofVelocities)
MOCHI_FIELD(dt)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerBasicJscPdTarget)
MOCHI_FIELD(targetPose)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ControllerBasicJscPd)
MOCHI_BASE_CLASS(superdex::robotics::ControllerBase)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::SensorBase)
MOCHI_BASE_CLASS(superdex::robotics::ComponentBase)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::ActuatorBase)
MOCHI_BASE_CLASS(superdex::robotics::ComponentBase)
MOCHI_STRUCT_END_EX()

MOCHI_STRUCT_BEGIN_EX(superdex::robotics::CameraSensor)
MOCHI_BASE_CLASS(superdex::robotics::SensorBase)
MOCHI_STRUCT_END_EX()

// clang-format on
